spring:
  profiles:
    active: test  # Set the active profile to 'prod' for production

---

spring:
  datasource:
    username: root
    password: lanyu8854
    url: jdbc:mysql:///doginfo
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod

server:
  port: 3070

---

server:
  port: 1010

spring:
  datasource:
    username: root
    password: lanyu8854
    url: jdbc:mysql:///doginfo_test
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: test
  web:
    resources:
      add-mappings: true

  jpa:
    hibernate:
      use-new-id-generator-mappings: false

aliyun:
  oss:
    endpoint: https://oss-eu-west-1.aliyuncs.com
    accessKeyId: LTAI5tAuHfoTvgbcbij4px3d
    accessKeySecret: RbUesjwGoiJhjV3b54Hl9WoW6yCy6F
    bucketName: dog-shelter-system

